### ISSUE TITLE
how to create the train data ?

### ISSUE THREAD

**Issue by iamsile** [strnam/sequential_short_text_classification#1]
Hi, strname
I want to use the code to do some test. But I don't know how to create the data of train, especially the input format. Can you give me some advise? 

My input data format is [[doc, sentence, words]] that is a 4D-tensor.

Look forward to your favourable reply. Thank you

**Comment by iamsile** [comment]
I finished

**Comment by strnam** [comment]
Hi @iamsile,

I'm glad if you can update some new examples for this code. I jus tested on Switchboard dataset as the  author of this paper.
Also, I just update the code to run example, It's messy but hope it's can useful for you.
